name: Build Android APK
on: [push]

env:
  # Убираем предупреждение о Node.js 20
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libvlc-dev libmpv-dev

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Build APK
        run: |
          pip install flet
          # Собираем для всех типов процессоров (чтобы точно открылось)
          # Пока без сложных библиотек, только база
          flet build apk --include-all-platforms --verbose
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: jarvis-apk
          path: build/apk/*.apk
